FROM public.ecr.aws/lambda/python:3.11

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR ${LAMBDA_TASK_ROOT}

COPY backend/requirements-lambda.txt .
RUN python -m pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements-lambda.txt

COPY backend/app ./app
COPY backend/resources ./resources

CMD ["app.lambda_handler.handler"]
